-- MySQL Script generated by MySQL Workbench
-- sáb 17 mar 2018 13:47:31 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Discografia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Discografia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Discografia` DEFAULT CHARACTER SET utf8 ;
USE `Discografia` ;

-- -----------------------------------------------------
-- Table `Discografia`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Discografia`.`Genero` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(45) NULL,
  PRIMARY KEY (`idGenero`),
  UNIQUE INDEX `genero_UNIQUE` (`genero` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Discografia`.`Disco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Discografia`.`Disco` (
  `idDisco` INT(11) NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(145) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Autor` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Formato` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Genero` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ISMN` VARCHAR(16) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Sello_discografico` VARCHAR(145) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Clasificacion` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Genero_idGenero` INT NOT NULL,
  PRIMARY KEY (`idDisco`, `Genero_idGenero`),
  UNIQUE INDEX `idDisco_UNIQUE` (`idDisco` ASC),
  INDEX `fk_Disco_Genero1_idx` (`Genero_idGenero` ASC),
  CONSTRAINT `fk_Disco_Genero1`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `Discografia`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `Discografia`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Discografia`.`Stock` (
  `idStock` INT(11) NOT NULL,
  `Cantidad` INT(11) NULL DEFAULT NULL,
  `Fecha_ingreso` DATETIME NULL DEFAULT NULL,
  `Fecha_egreso` DATETIME NULL DEFAULT NULL,
  `Disco_idDisco` INT(11) NOT NULL,
  PRIMARY KEY (`idStock`),
  INDEX `fk_Stock_Disco_idx` (`Disco_idDisco` ASC),
  CONSTRAINT `fk_Stock_Disco`
    FOREIGN KEY (`Disco_idDisco`)
    REFERENCES `Discografia`.`Disco` (`idDisco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
