-- MySQL Script generated by MySQL Workbench
-- mié 14 mar 2018 16:18:10 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema Discografia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Discografia` ;

-- -----------------------------------------------------
-- Schema Discografia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Discografia` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Discografia` ;

-- -----------------------------------------------------
-- Table `Disco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Disco` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Disco` (
  `idDisco` INT(11) NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(145) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Autor` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Formato` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Genero` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ISMN` VARCHAR(16) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Sello_discografico` VARCHAR(145) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Clasificacion` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`idDisco`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idDisco_UNIQUE` ON `Disco` (`idDisco` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stock` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Stock` (
  `idStock` INT(11) NOT NULL,
  `Cantidad` INT(11) NULL DEFAULT NULL,
  `Fecha_ingreso` DATETIME NULL DEFAULT NULL,
  `Fecha_egreso` DATETIME NULL DEFAULT NULL,
  `Disco_idDisco` INT(11) NOT NULL,
  PRIMARY KEY (`idStock`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
